name: Verify Solutions

on:
  workflow_dispatch:
  push:

jobs:
  verify-solutions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./verify_solutions.sh
